---
- name: Restart Apache server
  hosts: "{{ ansible_eda.event.rootCauseEntity.name }}"
  become: true
  tasks:

    - name: Execute fix_cpu.sh
      command: /usr/local/bin/fix_cpu.sh
      register: script_output
      ignore_errors: yes  # Optional: Continue even if the script fails

    - name: Display the output of the script
      debug:
        var: script_output.stdout
      